// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  gnexaSidebar: [
    {
      type: 'category',
      label: 'The Big Picture',
      items: [
        'overview/vision',
        'overview/tech-stack',
        'overview/high-level-architecture',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'The Components',
      items: [
        'components/user-service',
        'components/product-service',
        'components/order-service',
        'components/finance-service',
        'components/media-service',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'The Hard Things',
      items: [
        'engineering/saga-pattern',
        'engineering/race-conditions',
        'engineering/idempotency',
        'engineering/payment-aggregation',
        'engineering/polyglot-orchestration',
      ],
      collapsed: false,
    },
  ],
};

export default sidebars;
